name: Update GitHub Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "5 0/4 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
        name: production
    permissions:
        contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: sanurb
          template: classic
          base: ""
          config_timezone: GMT-5
          filename: assets/gen/metrics.svg
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: scss, css, jupyter notebook, html
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          commits_authoring: Santiago Urbano, sanurb, sanurb@users.noreply.github.com
          plugin_languages_details: lines, percentage
          plugin_languages_other: no
        
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
            filename: assets/gen/chievements.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            output_action: gist
            committer_gist: ${{ secrets.METRICS_TOKEN }}
            plugin_achievements: yes
            plugin_achievements_display: compact
            plugin_fortune: yes